apiVersion: v1
kind: Secret
metadata:
  name: legacy-code-ecommerce-secret
  namespace: stage
type: Opaque
stringData:
  DB_URL: "jdbc:mysql://54.227.6.75:8044/ecommerce"
  DB_USER: "root"
  DB_PASS: "wmPS#legacy"
