apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: {{ .Values.app.image }}
        ports:
        - containerPort: {{ .Values.app.port }}
        imagePullPolicy: Always

        envFrom:
        - secretRef:
            name: {{ .Values.secret.name }}

        resources:
          {{- toYaml .Values.resources | nindent 10 }}

      imagePullSecrets:
      {{- toYaml .Values.imagePullSecrets | nindent 6 }}
